config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [ :show ]
  devise_for :users
  resources :events do
    resources :event_attendances, only: [ :create, :destroy ]
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "events#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :creator, class_name: "User"
  has_many :event_attendances
  has_many :attendees, through: :event_attendances, source: :user

  scope :past, -> { where("date < ?", Date.today) }

  scope :upcoming, -> { where("date >= ?", Date.today) }
end

app/models/event_attendance.rb
class EventAttendance < ApplicationRecord
  belongs_to :user
  belongs_to :event
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :created_events, class_name: "Event", foreign_key: :creator_id
  has_many :event_attendances
  has_many :attended_events, through: :event_attendances, source: :event
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/event_attendances_controller.rb
class EventAttendancesController < ApplicationController
  before_action :set_event

  def create
    @attendance = @event.event_attendances.build(user: current_user)

    if @attendance.save
      redirect_to @event, notice: "You are attending the event"
    else
      redirect_to @event, alert: "Could not join the event"
    end
  end

  def destroy
    @attendance = @event.event_attendances.find_by(user: current_user)
    @attendance&.destroy
    redirect_to @event, notice: "You are no longer attending this event."
  end

  private

  def set_event
    @event = Event.find(params[:event_id])
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user!, only: [ :new, :create ]
  def index
    @events = Event.all
  end

  def show
    @event = Event.find(params[:id])
  end

  def new
    @event = current_user.created_events.build
  end

  def create
    @event = current_user.created_events.build(event_params)
    if @event.save
      redirect_to events_path, notice: "Event created successfully"
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def event_params
    params.expect(event: [ :date, :name, :details ])
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  def show
    @user = User.find(params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/event_attendances_helper.rb
module EventAttendancesHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/events/index.html.erb
<h1>Events</h1>
<% if user_signed_in? %>
    <%= button_to "Create Event", new_event_path, method: :get%>
    <%= button_to "My Profile", user_path(current_user)%>
<% end %>


<% @events.each do |event|%>
    <p><%= link_to event.name, event%></p>
    <p>Date: <%= event.date %></p>
<%end%>

<% if user_signed_in? %>
    <%= button_to "Sign out", destroy_user_session_path, method: :delete %>
<%else%>
    <%= link_to "Sign Up", new_user_registration_path%>
    <%= link_to "Sign In", new_user_session_path%>
<%end%>

app/views/events/new.html.erb
<%= form_with model: @event do |form|%>
    <%= form.label :name %>
    <%= form.text_field :name%>
    <%= form.label :date%>
    <%= form.date_field :date%>
    <%= form.label :details%>
    <%= form.text_field :details%>
    <%= form.submit%>
<%end%>

app/views/events/show.html.erb
<h1><%= @event.name%></h1>

<h2>Date: <%= @event.date%></h2>
<p><%= @event.details%></p>
<h2>Attendees: </h2>
<% @event.attendees.each do |attendee|%>
    <p><%= attendee.email%></p>
<%end%>

<% if user_signed_in? %>
    <% if @event.attendees.include?(current_user)%>
        <%= button_to "Leave Event", event_event_attendance_path(@event, @event.event_attendances.find_by(user: current_user)), method: :delete%>
    <%else%>
        <%= button_to "Join Event", event_event_attendances_path(@event), method: :post %>
    <%end%>
<%end%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Private Events" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/show.html.erb
<h1><%= @user.email%>'s Profile</h1>

<h2>Events created by <%= @user.email%>:</h2>

<% @user.created_events.each do |event|%>
    <p>Date: <%=event.date%><p>
    <p>Name: <%=event.name%><p>
<%end%>

<h2>Events attended by <%= @user.email%>:</h2>
<% @user.attended_events.past.each do |event|%>
    <p>Date: <%=event.date%><p>
    <p>Name: <%=event.name%><p>
<%end%>

<h2>Events to be attended by <%= @user.email%>:</h2>
<% @user.attended_events.upcoming.each do |event|%>
    <p>Date: <%=event.date%><p>
    <p>Name: <%=event.name%><p>
<%end%>